CREATE TABLE produtos (
    id_produto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL UNIQUE,
    categoria VARCHAR(20) NOT NULL,
    estoque_atual INT NOT NULL CHECK (estoque_atual >= 0),
    estoque_minimo INT NOT NULL CHECK (estoque_minimo >= 0),
    unidade_medida VARCHAR(20) NOT NULL,
    data_cadastro DATE NOT NULL
);
